### ISSUE TITLE
Custom UI

### ISSUE THREAD

**Issue by maxiaodegithub** [mono0926/barcode_scan2#13]
Android and IOS unified UI

**Comment by mono0926** [comment]
As written here, that request doesn't fit this package. Try to find other packages which meet the requirements.

> This provides a simple wrapper for two commonly used iOS and Android libraries:
iOS: https://github.com/mikebuss/MTBBarcodeScanner
Android: https://github.com/dm77/barcodescanner
> 
> https://github.com/mono0926/barcode_scan2#barcode_scan2
