### ISSUE TITLE
[Feature Request] Not full screen camera preview

### ISSUE THREAD

**Issue by prooshani** [mono0926/barcode_scan2#16]
Hi,

Is there anyway to contain the camera preview in a container?

I mean, if I call the `BarcodeScanner.scan()` it will open up a full screen camera panel so as to scan the barcode but, I want to open a specifically sized container to fit the camera preview, like a dialog box, for some reasons.

If it is possible please let me know.

Many thanks.

**Comment by mono0926** [comment]
It cannot be supported as noted https://github.com/mono0926/barcode_scan2/issues/13#issuecomment-833269243.
