### ISSUE TITLE
Java RuntimeException: Reply already submitted

### ISSUE THREAD

**Issue by justjew** [mono0926/barcode_scan2#23]
**BUG REPORTS WITHOUT PROVIDING THESE INFORMATIONS WILL BE CLOSED DIRECTLY. DON'T REMOVE THE SECTIONS!**

**Describe the bug**
The following exception has occured in producion. Got it in Sentry.

`Failure delivering result ResultInfo{who=null, request=100, result=-1, data=Intent { (has extras) }} to activity {ru.carmelrus.pdi/ru.carmelrus.pdi.MainActivity}: java.lang.IllegalStateException: Reply already submitted`

**To Reproduce**
Not sure

**Expected behavior**

**Screenshots**
![1625565743786](https://user-images.githubusercontent.com/15147974/124583130-fe4bd800-de52-11eb-85db-695e60c6731e.png)
![1625565836668](https://user-images.githubusercontent.com/15147974/124583152-03a92280-de53-11eb-8b7d-0163756e5458.png)
![1625565915515](https://user-images.githubusercontent.com/15147974/124583162-073ca980-de53-11eb-85d2-5a25c6ee365e.png)

**Logs**
[sentry-log.json.txt](https://github.com/mono0926/barcode_scan2/files/6769199/sentry-log.json.txt)
Here is the issue log from Sentry.

_p.s.
Could not load it here as .json, so it is .json.txt_

**Environment (please complete the following information):**
 - [x] Android? Version: 9
 - [x] Real Device? Which?: Samsung SM-T395
 - Version of `barcode_scan` ^4.1.3
 - Output of `flutter --version`: 
```
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (4 weeks ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

**Additional context**

**Comment by 0aps** [comment]
was able to reproduce this again on version 4.5.1 / flutter 3.35.4, when the Android app is using an activity-alias
