### ISSUE TITLE
Platform libraries are abandoned

### ISSUE THREAD

**Issue by luckv** [mono0926/barcode_scan2#38]
I was posing a question about this flutter plugin and its longevity. As a developer I would like to use code that is actively maintained, because of bugs.
That is a primary concern in the android ecosystem, where every 12 months a new major version of the os with breaking changes rolls out (the last two, android 12 and 11, introduces different breaking changes). 
I noticed that both the android and the ios libraries used by this plugin are abandoned.
What are your plans about this? Do you think to migrate to another library with the same functionalities?
This library is good, and thanks god someone continue to develop the original abandoned library and gave it nullsafety! 
But I have this question and it's important for me to know the answer.

**Comment by mono0926** [comment]
Not planned, but I'm welcome the pull request as described here: https://github.com/mono0926/barcode_scan2/discussions/3

And, there are other choices such as this: [flutter_barcode_scanner | Flutter Package](https://pub.dev/packages/flutter_barcode_scanner)
