### ISSUE TITLE
[Bug] Class 'ActivityHelper' is not abstract  when trying to compile to android?

### ISSUE THREAD

**Issue by nohkumado** [mono0926/barcode_scan2#48]
**BUG REPORTS WITHOUT PROVIDING THESE INFORMATIONS WILL BE CLOSED DIRECTLY. DON'T REMOVE THE SECTIONS!**

**Describe the bug**
i try to build a flutter app that scans a QR code, but it fails in the lib directly??

**To Reproduce**
follow the instructions to enable the barcode_scan2 lib (i added a 2 at each end of the name for pubspec dependency and lib include) 
and just try to compile it

**Expected behavior**
a working binary

**Screenshots**

**Logs**
Launching lib/main.dart on Pixel 4a in debug mode...
Running Gradle task 'assembleCompleteDebug'...
e: /home/bboett/.pub-cache/hosted/pub.dartlang.org/barcode_scan2-4.2.0/android/src/main/kotlin/de/mintware/barcode_scan/ActivityHelper.kt: (16, 1): Class 'ActivityHelper' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /home/bboett/.pub-cache/hosted/pub.dartlang.org/barcode_scan2-4.2.0/android/src/main/kotlin/de/mintware/barcode_scan/ActivityHelper.kt: (71, 5): 'onRequestPermissionsResult' overrides nothing
e: /home/bboett/.pub-cache/hosted/pub.dartlang.org/barcode_scan2-4.2.0/android/src/main/kotlin/de/mintware/barcode_scan/ActivityHelper.kt: (81, 58): Type mismatch: inferred type is Array<CapturedType(out String)>? but Array<(out) String!> was expected
e: /home/bboett/.pub-cache/hosted/pub.dartlang.org/barcode_scan2-4.2.0/android/src/main/kotlin/de/mintware/barcode_scan/ActivityHelper.kt: (81, 71): Type mismatch: inferred type is IntArray? but IntArray was expected
e: /home/bboett/.pub-cache/hosted/pub.dartlang.org/barcode_scan2-4.2.0/android/src/main/kotlin/de/mintware/barcode_scan/ChannelHandler.kt: (64, 39): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected
e: /home/bboett/.pub-cache/hosted/pub.dartlang.org/barcode_scan2-4.2.0/android/src/main/kotlin/de/mintware/barcode_scan/RequestCameraPermissionHandler.kt: (8, 1): Class 'RequestCameraPermissionHandler' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /home/bboett/.pub-cache/hosted/pub.dartlang.org/barcode_scan2-4.2.0/android/src/main/kotlin/de/mintware/barcode_scan/RequestCameraPermissionHandler.kt: (11, 5): 'onRequestPermissionsResult' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':barcode_scan2:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Exception: Gradle task assembleCompleteDebug failed with exit code 1

**Environment (please complete the following information):**
 - [ ] iOS? Version: ...
 - [ ] Android? Version: 31
 - [ ] Real Device? Which?:  pixel 4a 
 - [ ] Emulator/Simulator?none.
 - Version of `barcode_scan` 4.2
 - Output of `flutter --version`: 
```
Flutter ...2.12.0-4.1.pre
```

**Additional context**

**Comment by nash81** [comment]
Were you able to find a resolution? facing same error

**Comment by robinbonnes** [comment]
I've created a PR here: https://github.com/mono0926/barcode_scan2/pull/50

You can use my repository for now, enter in your `pubspec.yaml`:

```
  barcode_scan2:
    git:
      url: https://github.com/robinbonnes/barcode_scan2
```
